import type { Metadata } from 'next';
import { Caveat, Average_Sans, Syne_Mono } from 'next/font/google';
import './globals.css';

const caveat = Caveat({ subsets: ['latin'], variable: '--font-caveat' });
const averageSans = Average_Sans({ weight: '400', subsets: ['latin'], variable: '--font-average' });
const syneMono = Syne_Mono({ weight: '400', subsets: ['latin'], variable: '--font-syne' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${caveat.variable} ${averageSans.variable} ${syneMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
